"""feat: implement basic model for links

Revision ID: 641be97ad9a1
Revises: eb86ff8b08f1
Create Date: 2024-04-21 10:29:37.485249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641be97ad9a1'
down_revision: Union[str, None] = 'eb86ff8b08f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
