"""feat: implement association clicks with user and links

Revision ID: 84eb4338b576
Revises: 51e3da169529
Create Date: 2024-04-21 16:11:03.910690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84eb4338b576'
down_revision: Union[str, None] = '51e3da169529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_clicks',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('link_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link_clicks')
    # ### end Alembic commands ###
