"""fix: backpopulates in LinkModel

Revision ID: a78a4c6fa655
Revises: 427aeaf8b09e
Create Date: 2024-04-21 11:06:22.983499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a78a4c6fa655'
down_revision: Union[str, None] = '427aeaf8b09e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
