"""feat: add additional fields to link_clicks - 2

Revision ID: bab115362df0
Revises: 3030a049d1d5
Create Date: 2024-04-21 16:38:39.681815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab115362df0'
down_revision: Union[str, None] = '3030a049d1d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_clicks', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link_clicks', 'created')
    # ### end Alembic commands ###
