"""feat: add unique click to link clicks

Revision ID: e90c467cc339
Revises: bab115362df0
Create Date: 2024-04-22 19:29:35.315276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90c467cc339'
down_revision: Union[str, None] = 'bab115362df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_link', 'link_clicks', ['user_id', 'link_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_link', 'link_clicks', type_='unique')
    # ### end Alembic commands ###
