"""feat: delete refresh_token_expire in TokenModel

Revision ID: eb86ff8b08f1
Revises: fde1baf21a51
Create Date: 2024-04-18 21:01:57.415955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb86ff8b08f1'
down_revision: Union[str, None] = 'fde1baf21a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'refresh_token_expire')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('refresh_token_expire', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###
