"""fix: typo in TokenModel

Revision ID: fde1baf21a51
Revises: 56da6a1a12e8
Create Date: 2024-04-18 20:58:21.781298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde1baf21a51'
down_revision: Union[str, None] = '56da6a1a12e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('refresh_token', sa.String(), nullable=False))
    op.drop_column('tokens', 'reshresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('reshresh_token', sa.VARCHAR(), nullable=False))
    op.drop_column('tokens', 'refresh_token')
    # ### end Alembic commands ###
